update_fastlane

default_platform(:ios)

platform :ios do
  lane :bump_and_push_pods do |options|
    desc "Push library pods"

    if options[:bump]
      bump_type = options[:bump]
    else
      commit = last_git_commit
      parsed_commit = commit[:message].match(/\[([a-z]+)\:([a-z]+)\]/)

      if parsed_commit
        bump_type = parsed_commit[2]
      end
    end

    if !bump_type
      bump_type = "patch"
    end

    pod_sources = ["https://#{ ENV['GIT_PERSONAL_ACCESS_TOKEN'] }github.com/sw-code/spotar-ios-pods", "https://cdn.cocoapods.org/"]
    # pod_lib_lint(podspec: "Turf.podspec", sources: pod_sources, allow_warnings: true)
    # pod_lib_lint(podspec: "MapboxSpeech.podspec", sources: pod_sources, allow_warnings: true)
    # pod_lib_lint(podspec: "MapboxGeocoder.podspec", sources: pod_sources, allow_warnings: true)
    # pod_lib_lint(podspec: "MapboxDirections.podspec", sources: pod_sources, allow_warnings: true)
    # pod_lib_lint(podspec: "MapboxCoreNavigation.podspec", sources: pod_sources, include_podspecs: "{Turf.podspec,MapboxDirections.podspec}", allow_warnings: true)
    # pod_lib_lint(podspec: "MapboxNavigation.podspec", sources: pod_sources, include_podspecs: "{MapboxCoreNavigation.podspec,MapboxDirections.podspec,MapboxGeocoder.podspec,MapboxSpeech.podspec,Turf.podspec}", allow_warnings: true)
    # pod_lib_lint(podspec: "MapboxNavigationUI.podspec", sources: pod_sources, include_podspecs: "{MapboxCoreNavigation.podspec,MapboxNavigation.podspec,MapboxDirections.podspec,MapboxGeocoder.podspec,MapboxSpeech.podspec,Turf.podspec}", allow_warnings: true)

    bump_pod(pod: "Turf.podspec", bump: bump_type, project: "./MapboxNavigation.xcodeproj", target: "Turf")
    bump_pod(pod: "MapboxSpeech.podspec", bump: bump_type, project: "./MapboxNavigation.xcodeproj", target: "MapboxSpeech")
    bump_pod(pod: "MapboxGeocoder.podspec", bump: bump_type, project: "./MapboxNavigation.xcodeproj", target: "MapboxGeocoder")
    bump_pod(pod: "MapboxDirections.podspec", bump: bump_type, project: "./MapboxNavigation.xcodeproj", target: "MapboxDirections")
    bump_pod(pod: "MapboxCoreNavigation.podspec", bump: bump_type, project: "./MapboxNavigation.xcodeproj", target: "MapboxCoreNavigation")
    bump_pod(pod: "MapboxNavigation.podspec", bump: bump_type, project: "./MapboxNavigation.xcodeproj", target: "MapboxNavigation")
    bump_pod(pod: "MapboxNavigationUI.podspec", bump: bump_type, project: "./MapboxNavigation.xcodeproj", target: "MapboxNavigationUI")

    version = get_version_number_from_xcodeproj(
      xcodeproj: "./MapboxNavigation.xcodeproj",
      target: "MapboxNavigationUI"
    )
    
    change_podspec_dependency_version(podspec: "MapboxCoreNavigation.podspec", dependency: "Turf", version: version)
    change_podspec_dependency_version(podspec: "MapboxCoreNavigation.podspec", dependency: "MapboxDirections", version: version)

    change_podspec_dependency_version(podspec: "MapboxNavigation.podspec", dependency: "MapboxCoreNavigation", version: version)
    change_podspec_dependency_version(podspec: "MapboxNavigation.podspec", dependency: "MapboxDirections", version: version)
    change_podspec_dependency_version(podspec: "MapboxNavigation.podspec", dependency: "MapboxGeocoder", version: version)
    change_podspec_dependency_version(podspec: "MapboxNavigation.podspec", dependency: "MapboxSpeech", version: version)
    change_podspec_dependency_version(podspec: "MapboxNavigation.podspec", dependency: "Turf", version: version)

    change_podspec_dependency_version(podspec: "MapboxNavigationUI.podspec", dependency: "MapboxCoreNavigation", version: version)
    change_podspec_dependency_version(podspec: "MapboxNavigationUI.podspec", dependency: "MapboxNavigation", version: version)
    change_podspec_dependency_version(podspec: "MapboxNavigationUI.podspec", dependency: "MapboxDirections", version: version)

    git_add
    git_commit(path: ".", message: "[skip ci] Version Bump to #{version}")
    add_git_tag(tag: version)
    push_to_git_remote(
      tags: true,
      set_upstream: true,
      remote_branch: "master"
    )

    pod_repo = "sw-code"
    pod_push(path: "Turf.podspec", sources: pod_sources, repo: pod_repo, skip_import_validation: true, skip_tests: true, allow_warnings: true)
    pod_push(path: "MapboxSpeech.podspec", sources: pod_sources, repo: pod_repo, skip_import_validation: true, skip_tests: true, allow_warnings: true)
    pod_push(path: "MapboxGeocoder.podspec", sources: pod_sources, repo: pod_repo, skip_import_validation: true, skip_tests: true, allow_warnings: true)
    pod_push(path: "MapboxDirections.podspec", sources: pod_sources, repo: pod_repo, skip_import_validation: true, skip_tests: true, allow_warnings: true)
    pod_push(path: "MapboxCoreNavigation.podspec", sources: pod_sources, repo: pod_repo, skip_import_validation: true, skip_tests: true, allow_warnings: true)
    pod_push(path: "MapboxNavigation.podspec", sources: pod_sources, repo: pod_repo, skip_import_validation: true, skip_tests: true, allow_warnings: true)
    pod_push(path: "MapboxNavigationUI.podspec", sources: pod_sources, repo: pod_repo, skip_import_validation: true, skip_tests: true, allow_warnings: true)
  end

  lane :bump_pod do |options|
    pod = options[:pod]
    bump_type = options[:bump]
    project_file = options[:project]
    project_target = options[:target]
    version = version_bump_podspec(
      path: pod,
      bump_type: bump_type
    )
    desc "Bump library pod #{pod} to #{version}"
    increment_build_number_in_xcodeproj(xcodeproj: project_file, target: project_target)
    increment_version_number_in_xcodeproj(version_number: version, xcodeproj: project_file, target: project_target)
  end
end